function DV=Calculate_acceleration_body(u)

Cnsts=u(1:22);
Inps=u(23:33);
Vels=u(34:39);
Pos=u(40:45);

jf1=Cnsts(1);jf2=Cnsts(2);jf3=Cnsts(3);jh1=Cnsts(4);jh2=Cnsts(5);jh3=Cnsts(6);
mf1=Cnsts(7);mf2=Cnsts(8);mf3=Cnsts(9);mh=Cnsts(10);mp=Cnsts(11);rbx=Cnsts(12);
m=Cnsts(13);g=Cnsts(14);kd0=Cnsts(15);kd=Cnsts(16);kl0=Cnsts(17);kl=Cnsts(18);
km0=Cnsts(19);km=Cnsts(20);k1=Cnsts(21);k2=Cnsts(22);

rpx=Inps(1);rpy=Inps(2);rpz=Inps(3);mb=Inps(4);
drpx=Inps(5);drpy=Inps(6);drpz=Inps(7);dmb=Inps(8);
d2rpx=Inps(9);d2rpy=Inps(10);d2rpz=Inps(11);

rb=[rbx;0;0];
rp=[rpx;rpy;rpz];
drp=[drpx;drpy;drpz];
d2rp=[d2rpx;d2rpy;d2rpz];

vx=Vels(1);vy=Vels(2);vz=Vels(3);
wx=Vels(4);wy=Vels(5);wz=Vels(6);

v=[vx;vy;vz];
w=[wx;wy;wz];

bx=Pos(1);by=Pos(2);bz=Pos(3);
phi=Pos(4);theta=Pos(5);psi=Pos(6);

b=[bx;by;bz];

I=Calculate_I(jf1,jf2,jf3,jh1,jh2,jh3,mb,mf1,mf2,mf3,mh,mp,rbx,rpx,rpy,rpz);
Iinv=Calculate_Iinv(jf1,jf2,jf3,jh1,jh2,jh3,mb,mf1,mf2,mf3,mh,mp,rbx,rpx,rpy,rpz);
dIinv=Calculate_dIinv(dmb,drpx,drpy,drpz,jf1,jf2,jf3,jh1,jh2,jh3,mb,mf1,mf2,mf3,mh,mp,rbx,rpx,rpy,rpz);

R=Calculate_R(phi,theta,psi);
alpha=atan2(vz,vx);
beta=atan2(vy,norm([vx;vz]));
Rwb=Calculate_Rwb(alpha,beta);

mv=mh+mp+mb;
rcgx=(mb*rbx+mp*rpx)/mv;
rcgy=(mp*rpy)/mv;
rcgz=(mp*rpz)/mv;
rcg=[rcgx;rcgy;rcgz];

[Fext,Mext]=Calculate_F_M(R,Rwb,mv,m,g,rcg,alpha,beta,kd0,kd,kl0,kl,km0,km,k1,k2,v,w);

temp=I*[v;w;drp];
Px=temp(1);Py=temp(2);Pz=temp(3);
PIx=temp(4);PIy=temp(5);PIz=temp(6);
Ppx=temp(7);Ppy=temp(8);Ppz=temp(9);

P=[Px;Py;Pz];
PI=[PIx;PIy;PIz];
Pp=[Ppx;Ppy;Ppz];

dP=cross(P,w)+Fext;
dPI=cross(PI,w)+Mext;

Z=Iinv(7:9,1:6)*[dP;dPI]+dIinv(7:9,1:9)*[P;PI;Pp];
Finv=Calculate_Finv(Iinv);
dPp=Finv*(d2rp-Z);

temp=Iinv(1:6,1:9)*[dP;dPI;dPp]+dIinv(1:6,1:9)*[P;PI;Pp];
dvx=temp(1);dvy=temp(2);dvz=temp(3);
dwx=temp(4);dwy=temp(5);dwz=temp(6);

dv=[dvx;dvy;dvz];
dw=[dwx;dwy;dwz];

DV=[dv;dw];

end

function I = Calculate_I(jf1,jf2,jf3,jh1,jh2,jh3,mb,mf1,mf2,mf3,mh,mp,rbx,rpx,rpy,rpz)
%CALCULATE_I
%    I = CALCULATE_I(JF1,JF2,JF3,JH1,JH2,JH3,MB,MF1,MF2,MF3,MH,MP,RBX,RPX,RPY,RPZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Mar-2021 11:47:15

t2 = mp.*rpz;
t3 = mb.*rbx;
t4 = mp.*rpx;
t5 = mp.*rpy;
t6 = -t3-t4;
t7 = rpz.^2;
t8 = mp.*t7;
t9 = t3+t4;
t10 = rbx.^2;
t11 = mb.*t10;
t12 = rpx.^2;
t13 = mp.*t12;
t14 = rpy.^2;
t15 = mp.*t14;
I = reshape([mb+mf1+mh+mp,0.0,0.0,0.0,t2,-t5,mp,0.0,0.0,0.0,mb+mf2+mh+mp,0.0,-t2,0.0,t9,0.0,mp,0.0,0.0,0.0,mb+mf3+mh+mp,t5,t6,0.0,0.0,0.0,mp,0.0,-t2,t5,jf1+jh1+t8+t15,-mp.*rpx.*rpy,-mp.*rpx.*rpz,0.0,-t2,t5,t2,0.0,t6,-mp.*rpx.*rpy,jf2+jh2+t8+t11+t13,-mp.*rpy.*rpz,t2,0.0,-t4,-mp.*rpy,t9,0.0,-mp.*rpx.*rpz,-mp.*rpy.*rpz,jf3+jh3+t11+t13+t15,-t5,t4,0.0,mp,0.0,0.0,0.0,t2,-t5,mp,0.0,0.0,0.0,mp,0.0,-t2,0.0,t4,0.0,mp,0.0,0.0,0.0,mp,t5,-t4,0.0,0.0,0.0,mp],[9,9]);
end

function Iinv = Calculate_Iinv(jf1,jf2,jf3,jh1,jh2,jh3,mb,mf1,mf2,mf3,mh,mp,rbx,rpx,rpy,rpz)
%CALCULATE_IINV
%    IINV = CALCULATE_IINV(JF1,JF2,JF3,JH1,JH2,JH3,MB,MF1,MF2,MF3,MH,MP,RBX,RPX,RPY,RPZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Mar-2021 11:47:18

t2 = mb+mf1+mh;
t3 = 1.0./t2;
t4 = rbx.^2;
t5 = jf3.*mb;
t6 = jh3.*mb;
t7 = jf3.*mf2;
t8 = jf3.*mh;
t9 = jh3.*mf2;
t10 = jh3.*mh;
t11 = mb.*mf2.*t4;
t12 = mb.*mh.*t4;
t13 = t5+t6+t7+t8+t9+t10+t11+t12;
t14 = 1.0./t13;
t15 = mb.*t4;
t16 = jf2.*mb;
t17 = jh2.*mb;
t18 = jf2.*mf3;
t19 = jf2.*mh;
t20 = jh2.*mf3;
t21 = jh2.*mh;
t22 = mb.*mf3.*t4;
t23 = t12+t16+t17+t18+t19+t20+t21+t22;
t24 = 1.0./t23;
t25 = jf1+jh1;
t26 = 1.0./t25;
t27 = mb.*rbx.*t24;
t28 = mb+mf3+mh;
t29 = mb+mf2+mh;
t30 = mb.*rpx;
t31 = mh.*rpx;
t32 = rpy.*t14.*t29;
t33 = mb.^2;
t34 = mh.^2;
t35 = t4.^2;
t36 = rpy.^2;
t37 = rpz.^2;
t38 = mf2.*rpx;
t40 = mb.*rbx;
t39 = t30+t31+t38-t40;
t41 = mf3.*rpx;
t46 = mb.*rbx.*rpx;
t42 = jf3+jh3+t15-t46;
t43 = rpz.*t26;
t44 = 1.0./mp;
t45 = rpx.^2;
t47 = t30+t31-t40+t41;
t48 = jf1.*mb.*mh.*t4;
t49 = jh1.*mb.*mh.*t4;
t50 = jf1.*mb.*mp.*t4;
t51 = jh1.*mb.*mp.*t4;
t52 = jf1.*mb.*mp.*t45;
t53 = jh1.*mb.*mp.*t45;
t54 = jf1.*mh.*mp.*t45;
t55 = jh1.*mh.*mp.*t45;
Iinv = reshape([t3,0.0,0.0,0.0,0.0,0.0,-t3,0.0,0.0,0.0,t14.*(jf3+jh3+t15),0.0,0.0,0.0,-mb.*rbx.*t14,-mb.*rbx.*rpy.*t14,-t14.*t42,0.0,0.0,0.0,t24.*(jf2+jh2+t15),0.0,t27,0.0,-mb.*rbx.*rpz.*t24,0.0,-t24.*(jf2+jh2+t15-t46),0.0,0.0,0.0,t26,0.0,0.0,0.0,t43,-rpy.*t26,0.0,0.0,t27,0.0,t24.*t28,0.0,-rpz.*t24.*t28,0.0,t24.*t47,0.0,-mb.*rbx.*t14,0.0,0.0,0.0,t14.*t29,t32,-t14.*t39,0.0,-t3,-mb.*rbx.*rpy.*t14,-mb.*rbx.*rpz.*t24,0.0,-rpz.*t24.*t28,t32,t3.*t14.*t24.*t44.*(jf2.*jf3.*mb.*t33+jf2.*jf3.*mb.*t34.*3.0+jf2.*jh3.*mb.*t33+jf3.*jh2.*mb.*t33+jf2.*jh3.*mb.*t34.*3.0+jf3.*jh2.*mb.*t34.*3.0+jh2.*jh3.*mb.*t33+jf2.*jf3.*mf1.*t33+jh2.*jh3.*mb.*t34.*3.0+jf2.*jf3.*mf1.*t34+jf2.*jf3.*mf2.*t33+jf2.*jf3.*mf2.*t34+jf2.*jf3.*mf3.*t33+jf2.*jf3.*mf3.*t34+jf2.*jf3.*mh.*t33.*3.0+jf2.*jf3.*mh.*t34+jf2.*jh3.*mf1.*t33+jf3.*jh2.*mf1.*t33+jf2.*jh3.*mf1.*t34+jf2.*jh3.*mf2.*t33+jf3.*jh2.*mf1.*t34+jf3.*jh2.*mf2.*t33+jf2.*jh3.*mf2.*t34+jf2.*jh3.*mf3.*t33+jf3.*jh2.*mf2.*t34+jf3.*jh2.*mf3.*t33+jf2.*jh3.*mf3.*t34+jf3.*jh2.*mf3.*t34+jf2.*jh3.*mh.*t33.*3.0+jf3.*jh2.*mh.*t33.*3.0+jf2.*jh3.*mh.*t34+jf3.*jh2.*mh.*t34+jh2.*jh3.*mf1.*t33+jh2.*jh3.*mf1.*t34+jh2.*jh3.*mf2.*t33+jh2.*jh3.*mf2.*t34+jh2.*jh3.*mf3.*t33+jh2.*jh3.*mf3.*t34+jh2.*jh3.*mh.*t33.*3.0+jh2.*jh3.*mh.*t34+jf2.*jf3.*mp.*t33+jf2.*jf3.*mp.*t34+jf2.*jh3.*mp.*t33+jf3.*jh2.*mp.*t33+jf2.*jh3.*mp.*t34+jf3.*jh2.*mp.*t34+jh2.*jh3.*mp.*t33+jh2.*jh3.*mp.*t34+jf2.*t4.*t33.*t34.*2.0+jf3.*t4.*t33.*t34.*2.0+jh2.*t4.*t33.*t34.*2.0+jh3.*t4.*t33.*t34.*2.0+mb.*t33.*t34.*t35+mf1.*t33.*t34.*t35+mf2.*t33.*t34.*t35+mf3.*t33.*t34.*t35+mh.*t33.*t34.*t35+mp.*t33.*t34.*t35+jf2.*jf3.*mb.*mf1.*mf2+jf2.*jf3.*mb.*mf1.*mf3+jf2.*jf3.*mb.*mf2.*mf3+jf2.*jf3.*mb.*mf1.*mh.*2.0+jf2.*jf3.*mb.*mf2.*mh.*2.0+jf2.*jf3.*mb.*mf3.*mh.*2.0+jf2.*jh3.*mb.*mf1.*mf2+jf3.*jh2.*mb.*mf1.*mf2+jf2.*jh3.*mb.*mf1.*mf3+jf3.*jh2.*mb.*mf1.*mf3+jf2.*jh3.*mb.*mf2.*mf3+jf3.*jh2.*mb.*mf2.*mf3+jf2.*jh3.*mb.*mf1.*mh.*2.0+jf3.*jh2.*mb.*mf1.*mh.*2.0+jf2.*jh3.*mb.*mf2.*mh.*2.0+jf3.*jh2.*mb.*mf2.*mh.*2.0+jf2.*jh3.*mb.*mf3.*mh.*2.0+jf3.*jh2.*mb.*mf3.*mh.*2.0+jh2.*jh3.*mb.*mf1.*mf2+jh2.*jh3.*mb.*mf1.*mf3+jh2.*jh3.*mb.*mf2.*mf3+jf2.*jf3.*mf1.*mf2.*mf3+jh2.*jh3.*mb.*mf1.*mh.*2.0+jh2.*jh3.*mb.*mf2.*mh.*2.0+jf2.*jf3.*mf1.*mf2.*mh+jh2.*jh3.*mb.*mf3.*mh.*2.0+jf2.*jf3.*mf1.*mf3.*mh+jf2.*jf3.*mf2.*mf3.*mh+jf2.*jh3.*mf1.*mf2.*mf3+jf3.*jh2.*mf1.*mf2.*mf3+jf2.*jh3.*mf1.*mf2.*mh+jf3.*jh2.*mf1.*mf2.*mh+jf2.*jh3.*mf1.*mf3.*mh+jf3.*jh2.*mf1.*mf3.*mh+jf2.*jh3.*mf2.*mf3.*mh+jf3.*jh2.*mf2.*mf3.*mh+jh2.*jh3.*mf1.*mf2.*mf3+jf2.*jf3.*mb.*mf2.*mp+jf2.*jf3.*mb.*mf3.*mp+jh2.*jh3.*mf1.*mf2.*mh+jh2.*jh3.*mf1.*mf3.*mh+jh2.*jh3.*mf2.*mf3.*mh+jf2.*jf3.*mb.*mh.*mp.*2.0+jf2.*jh3.*mb.*mf2.*mp+jf3.*jh2.*mb.*mf2.*mp+jf2.*jh3.*mb.*mf3.*mp+jf3.*jh2.*mb.*mf3.*mp+jf2.*jh3.*mb.*mh.*mp.*2.0+jf3.*jh2.*mb.*mh.*mp.*2.0+jh2.*jh3.*mb.*mf2.*mp+jh2.*jh3.*mb.*mf3.*mp+jf2.*jf3.*mf2.*mf3.*mp+jh2.*jh3.*mb.*mh.*mp.*2.0+jf2.*jf3.*mf2.*mh.*mp+jf2.*jf3.*mf3.*mh.*mp+jf2.*jh3.*mf2.*mf3.*mp+jf3.*jh2.*mf2.*mf3.*mp+jf2.*jh3.*mf2.*mh.*mp+jf3.*jh2.*mf2.*mh.*mp+jf2.*jh3.*mf3.*mh.*mp+jf3.*jh2.*mf3.*mh.*mp+jh2.*jh3.*mf2.*mf3.*mp+jh2.*jh3.*mf2.*mh.*mp+jh2.*jh3.*mf3.*mh.*mp+jf2.*mb.*mf1.*t4.*t34+jf2.*mb.*mf2.*t4.*t33+jf2.*mb.*mf2.*t4.*t34+jf3.*mb.*mf1.*t4.*t34+jf2.*mb.*mf3.*t4.*t34+jf3.*mb.*mf2.*t4.*t34+jf3.*mb.*mf3.*t4.*t33+jf3.*mb.*mf3.*t4.*t34+jf2.*mb.*mh.*t4.*t33+jf2.*mb.*mh.*t4.*t34+jf3.*mb.*mh.*t4.*t33+jf3.*mb.*mh.*t4.*t34+jh2.*mb.*mf1.*t4.*t34+jh2.*mb.*mf2.*t4.*t33+jh2.*mb.*mf2.*t4.*t34+jh3.*mb.*mf1.*t4.*t34+jh2.*mb.*mf3.*t4.*t34+jh3.*mb.*mf2.*t4.*t34+jh3.*mb.*mf3.*t4.*t33+jh3.*mb.*mf3.*t4.*t34+jh2.*mb.*mh.*t4.*t33+jh2.*mb.*mh.*t4.*t34+jh3.*mb.*mh.*t4.*t33+jh3.*mb.*mh.*t4.*t34+jf2.*mf1.*mf2.*t4.*t33+jf2.*mf2.*mf3.*t4.*t33+jf3.*mf1.*mf3.*t4.*t33+jf3.*mf2.*mf3.*t4.*t33+jf2.*mf1.*mh.*t4.*t33+jf2.*mf2.*mh.*t4.*t33.*2.0+jf3.*mf1.*mh.*t4.*t33+jf2.*mf3.*mh.*t4.*t33+jf3.*mf2.*mh.*t4.*t33+jh2.*mf1.*mf2.*t4.*t33+jf3.*mf3.*mh.*t4.*t33.*2.0+jh2.*mf2.*mf3.*t4.*t33+jh3.*mf1.*mf3.*t4.*t33+jh3.*mf2.*mf3.*t4.*t33+jh2.*mf1.*mh.*t4.*t33+jh2.*mf2.*mh.*t4.*t33.*2.0+jh3.*mf1.*mh.*t4.*t33+jh2.*mf3.*mh.*t4.*t33+jh3.*mf2.*mh.*t4.*t33+jh3.*mf3.*mh.*t4.*t33.*2.0+jf2.*mb.*mp.*t4.*t34+jf3.*mb.*mp.*t4.*t34+jf2.*mb.*mp.*t33.*t36+jf2.*mb.*mp.*t34.*t36.*3.0+jf3.*mb.*mp.*t33.*t37+jf3.*mb.*mp.*t34.*t37.*3.0+jh2.*mb.*mp.*t4.*t34+jh3.*mb.*mp.*t4.*t34+jh2.*mb.*mp.*t33.*t36+jh2.*mb.*mp.*t34.*t36.*3.0+jh3.*mb.*mp.*t33.*t37+jh3.*mb.*mp.*t34.*t37.*3.0+jf2.*mf2.*mp.*t4.*t33+jf3.*mf3.*mp.*t4.*t33+jf2.*mf1.*mp.*t33.*t36+jf2.*mf1.*mp.*t34.*t36+jf2.*mf2.*mp.*t33.*t36+jf2.*mf2.*mp.*t34.*t36+jf2.*mf3.*mp.*t33.*t36+jf3.*mf1.*mp.*t33.*t37+jf2.*mf3.*mp.*t34.*t36+jf3.*mf1.*mp.*t34.*t37+jf3.*mf2.*mp.*t33.*t37+jf3.*mf2.*mp.*t34.*t37+jf3.*mf3.*mp.*t33.*t37+jf3.*mf3.*mp.*t34.*t37+jf2.*mh.*mp.*t4.*t33+jf3.*mh.*mp.*t4.*t33+jh2.*mf2.*mp.*t4.*t33+jh3.*mf3.*mp.*t4.*t33+jf2.*mh.*mp.*t33.*t36.*3.0+jf2.*mh.*mp.*t34.*t36+jh2.*mf1.*mp.*t33.*t36+jf3.*mh.*mp.*t33.*t37.*3.0+jh2.*mf1.*mp.*t34.*t36+jh2.*mf2.*mp.*t33.*t36+jf3.*mh.*mp.*t34.*t37+jh2.*mf2.*mp.*t34.*t36+jh2.*mf3.*mp.*t33.*t36+jh3.*mf1.*mp.*t33.*t37+jh2.*mf3.*mp.*t34.*t36+jh3.*mf1.*mp.*t34.*t37+jh3.*mf2.*mp.*t33.*t37+jh3.*mf2.*mp.*t34.*t37+jh3.*mf3.*mp.*t33.*t37+jh3.*mf3.*mp.*t34.*t37+jh2.*mh.*mp.*t4.*t33+jh3.*mh.*mp.*t4.*t33+jh2.*mh.*mp.*t33.*t36.*3.0+jh2.*mh.*mp.*t34.*t36+jh3.*mh.*mp.*t33.*t37.*3.0+jh3.*mh.*mp.*t34.*t37+mb.*mf2.*mf3.*t33.*t35+mb.*mf2.*mh.*t33.*t35+mb.*mf3.*mh.*t33.*t35+mf1.*mf2.*mf3.*t33.*t35+mf1.*mf2.*mh.*t33.*t35+mf1.*mf3.*mh.*t33.*t35+mf2.*mf3.*mh.*t33.*t35+mf2.*mf3.*mp.*t33.*t35+mf2.*mh.*mp.*t33.*t35+mf3.*mh.*mp.*t33.*t35+mp.*t4.*t33.*t34.*t36.*2.0+mp.*t4.*t33.*t34.*t37.*2.0+mb.*mf1.*mp.*t4.*t34.*t36+mb.*mf1.*mp.*t4.*t34.*t37+mb.*mf2.*mp.*t4.*t33.*t37+mb.*mf2.*mp.*t4.*t34.*t36+mb.*mf3.*mp.*t4.*t33.*t36+mb.*mf2.*mp.*t4.*t34.*t37+mb.*mf3.*mp.*t4.*t34.*t36+mb.*mf3.*mp.*t4.*t34.*t37+mb.*mh.*mp.*t4.*t33.*t36+mb.*mh.*mp.*t4.*t33.*t37+mb.*mh.*mp.*t4.*t34.*t36+mb.*mh.*mp.*t4.*t34.*t37+mf1.*mf2.*mp.*t4.*t33.*t37+mf1.*mf3.*mp.*t4.*t33.*t36+mf2.*mf3.*mp.*t4.*t33.*t36+mf2.*mf3.*mp.*t4.*t33.*t37+mf1.*mh.*mp.*t4.*t33.*t36+mf1.*mh.*mp.*t4.*t33.*t37+mf2.*mh.*mp.*t4.*t33.*t36+mf2.*mh.*mp.*t4.*t33.*t37.*2.0+mf3.*mh.*mp.*t4.*t33.*t36.*2.0+mf3.*mh.*mp.*t4.*t33.*t37+jf2.*mb.*mf1.*mf2.*mf3.*t4+jf3.*mb.*mf1.*mf2.*mf3.*t4+jf2.*mb.*mf1.*mf2.*mh.*t4+jf2.*mb.*mf1.*mf3.*mh.*t4+jf3.*mb.*mf1.*mf2.*mh.*t4+jf2.*mb.*mf2.*mf3.*mh.*t4+jf3.*mb.*mf1.*mf3.*mh.*t4+jf3.*mb.*mf2.*mf3.*mh.*t4+jh2.*mb.*mf1.*mf2.*mf3.*t4+jh3.*mb.*mf1.*mf2.*mf3.*t4+jh2.*mb.*mf1.*mf2.*mh.*t4+jh2.*mb.*mf1.*mf3.*mh.*t4+jh3.*mb.*mf1.*mf2.*mh.*t4+jh2.*mb.*mf2.*mf3.*mh.*t4+jh3.*mb.*mf1.*mf3.*mh.*t4+jh3.*mb.*mf2.*mf3.*mh.*t4+jf2.*mb.*mf2.*mf3.*mp.*t4+jf3.*mb.*mf2.*mf3.*mp.*t4+jf2.*mb.*mf1.*mf2.*mp.*t36+jf2.*mb.*mf1.*mf3.*mp.*t36+jf2.*mb.*mf2.*mf3.*mp.*t36+jf3.*mb.*mf1.*mf2.*mp.*t37+jf3.*mb.*mf1.*mf3.*mp.*t37+jf3.*mb.*mf2.*mf3.*mp.*t37+jf2.*mb.*mf2.*mh.*mp.*t4+jf2.*mb.*mf3.*mh.*mp.*t4+jf3.*mb.*mf2.*mh.*mp.*t4+jf3.*mb.*mf3.*mh.*mp.*t4+jh2.*mb.*mf2.*mf3.*mp.*t4+jh3.*mb.*mf2.*mf3.*mp.*t4+jf2.*mb.*mf1.*mh.*mp.*t36.*2.0+jf2.*mb.*mf2.*mh.*mp.*t36.*2.0+jf2.*mb.*mf3.*mh.*mp.*t36.*2.0+jf3.*mb.*mf1.*mh.*mp.*t37.*2.0+jh2.*mb.*mf1.*mf2.*mp.*t36+jf3.*mb.*mf2.*mh.*mp.*t37.*2.0+jh2.*mb.*mf1.*mf3.*mp.*t36+jf3.*mb.*mf3.*mh.*mp.*t37.*2.0+jh2.*mb.*mf2.*mf3.*mp.*t36+jh3.*mb.*mf1.*mf2.*mp.*t37+jh3.*mb.*mf1.*mf3.*mp.*t37+jh3.*mb.*mf2.*mf3.*mp.*t37+jh2.*mb.*mf2.*mh.*mp.*t4+jh2.*mb.*mf3.*mh.*mp.*t4+jh3.*mb.*mf2.*mh.*mp.*t4+jh3.*mb.*mf3.*mh.*mp.*t4+jh2.*mb.*mf1.*mh.*mp.*t36.*2.0+jh2.*mb.*mf2.*mh.*mp.*t36.*2.0+jh2.*mb.*mf3.*mh.*mp.*t36.*2.0+jh3.*mb.*mf1.*mh.*mp.*t37.*2.0+jh3.*mb.*mf2.*mh.*mp.*t37.*2.0+jh3.*mb.*mf3.*mh.*mp.*t37.*2.0+jf2.*mf1.*mf2.*mf3.*mp.*t36+jf3.*mf1.*mf2.*mf3.*mp.*t37+jf2.*mf1.*mf2.*mh.*mp.*t36+jf2.*mf1.*mf3.*mh.*mp.*t36+jf2.*mf2.*mf3.*mh.*mp.*t36+jf3.*mf1.*mf2.*mh.*mp.*t37+jf3.*mf1.*mf3.*mh.*mp.*t37+jh2.*mf1.*mf2.*mf3.*mp.*t36+jf3.*mf2.*mf3.*mh.*mp.*t37+jh3.*mf1.*mf2.*mf3.*mp.*t37+jh2.*mf1.*mf2.*mh.*mp.*t36+jh2.*mf1.*mf3.*mh.*mp.*t36+jh2.*mf2.*mf3.*mh.*mp.*t36+jh3.*mf1.*mf2.*mh.*mp.*t37+jh3.*mf1.*mf3.*mh.*mp.*t37+jh3.*mf2.*mf3.*mh.*mp.*t37+mb.*mf1.*mf2.*mf3.*mp.*t4.*t36+mb.*mf1.*mf2.*mf3.*mp.*t4.*t37+mb.*mf1.*mf2.*mh.*mp.*t4.*t36+mb.*mf1.*mf2.*mh.*mp.*t4.*t37+mb.*mf1.*mf3.*mh.*mp.*t4.*t36+mb.*mf1.*mf3.*mh.*mp.*t4.*t37+mb.*mf2.*mf3.*mh.*mp.*t4.*t36+mb.*mf2.*mf3.*mh.*mp.*t4.*t37),-rpy.*t14.*t39,-rpz.*t24.*t47,0.0,-t14.*t42,0.0,t43,0.0,-t14.*t39,-rpy.*t14.*t39,t14.*t26.*t44.*(t48+t49+t50+t51+t52+t53+t54+t55+jf1.*jf3.*mb+jf1.*jh3.*mb+jf3.*jh1.*mb+jh1.*jh3.*mb+jf1.*jf3.*mf2+jf1.*jf3.*mh+jf1.*jh3.*mf2+jf3.*jh1.*mf2+jf1.*jh3.*mh+jf3.*jh1.*mh+jh1.*jh3.*mf2+jh1.*jh3.*mh+jf1.*jf3.*mp+jf1.*jh3.*mp+jf3.*jh1.*mp+jh1.*jh3.*mp+jf1.*mb.*mf2.*t4+jh1.*mb.*mf2.*t4+jf3.*mb.*mp.*t37+jh3.*mb.*mp.*t37+jf3.*mf2.*mp.*t37+jf1.*mf2.*mp.*t45+jf3.*mh.*mp.*t37+jh3.*mf2.*mp.*t37+jh1.*mf2.*mp.*t45+jh3.*mh.*mp.*t37-jf1.*mb.*mp.*rbx.*rpx.*2.0-jh1.*mb.*mp.*rbx.*rpx.*2.0+mb.*mf2.*mp.*t4.*t37+mb.*mh.*mp.*t4.*t37),-rpy.*rpz.*t26,0.0,0.0,-t24.*(jf2+jh2+t15-mb.*rbx.*rpx),-rpy.*t26,t24.*(t30+t31+t41-mb.*rbx),0.0,-rpz.*t24.*t47,-rpy.*rpz.*t26,t24.*t26.*t44.*(t48+t49+t50+t51+t52+t53+t54+t55+jf1.*jf2.*mb+jf1.*jh2.*mb+jf2.*jh1.*mb+jh1.*jh2.*mb+jf1.*jf2.*mf3+jf1.*jf2.*mh+jf1.*jh2.*mf3+jf2.*jh1.*mf3+jf1.*jh2.*mh+jf2.*jh1.*mh+jh1.*jh2.*mf3+jh1.*jh2.*mh+jf1.*jf2.*mp+jf1.*jh2.*mp+jf2.*jh1.*mp+jh1.*jh2.*mp+jf1.*mb.*mf3.*t4+jh1.*mb.*mf3.*t4+jf2.*mb.*mp.*t36+jh2.*mb.*mp.*t36+jf2.*mf3.*mp.*t36+jf1.*mf3.*mp.*t45+jf2.*mh.*mp.*t36+jh2.*mf3.*mp.*t36+jh1.*mf3.*mp.*t45+jh2.*mh.*mp.*t36-jf1.*mb.*mp.*rbx.*rpx.*2.0-jh1.*mb.*mp.*rbx.*rpx.*2.0+mb.*mf3.*mp.*t4.*t36+mb.*mh.*mp.*t4.*t36)],[9,9]);
end

function dIinv = Calculate_dIinv(dmb,drpx,drpy,drpz,jf1,jf2,jf3,jh1,jh2,jh3,mb,mf1,mf2,mf3,mh,mp,rbx,rpx,rpy,rpz)
%CALCULATE_DIINV
%    DIINV = CALCULATE_DIINV(DMB,DRPX,DRPY,DRPZ,JF1,JF2,JF3,JH1,JH2,JH3,MB,MF1,MF2,MF3,MH,MP,RBX,RPX,RPY,RPZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Mar-2021 11:48:01

t2 = mb+mf1+mh;
t3 = 1.0./t2.^2;
t4 = jf3+jh3;
t5 = rbx.^2;
t6 = jf3.*mb;
t7 = jh3.*mb;
t8 = jf3.*mf2;
t9 = jf3.*mh;
t10 = jh3.*mf2;
t11 = jh3.*mh;
t12 = mb.*mf2.*t5;
t13 = mb.*mh.*t5;
t14 = t6+t7+t8+t9+t10+t11+t12+t13;
t15 = 1.0./t14.^2;
t16 = mb.^2;
t17 = jf2+jh2;
t18 = jf2.*mb;
t19 = jh2.*mb;
t20 = jf2.*mf3;
t21 = jf2.*mh;
t22 = jh2.*mf3;
t23 = jh2.*mh;
t24 = mb.*mf3.*t5;
t25 = t13+t18+t19+t20+t21+t22+t23+t24;
t26 = 1.0./t25.^2;
t27 = drpx.*mh.*rbx.*t5.*t16;
t28 = jf1+jh1;
t29 = 1.0./t28;
t30 = mf3+mh;
t31 = dmb.*rbx.*t17.*t26.*t30;
t32 = drpz.*jf2.*t16;
t33 = drpz.*jh2.*t16;
t34 = mf3.^2;
t35 = mh.^2;
t36 = drpz.*mf3.*t5.*t16;
t37 = drpz.*mh.*t5.*t16;
t38 = mf2+mh;
t39 = drpy.*jf3.*t16;
t40 = drpy.*jh3.*t16;
t41 = mf2.^2;
t42 = drpy.*mf2.*t5.*t16;
t43 = drpy.*mh.*t5.*t16;
t44 = drpx.*mb.*t5.*t35;
t45 = drpx.*mh.*t5.*t16;
t46 = dmb.*t3;
t47 = drpy.*jf3.*mb.*mf2;
t48 = drpy.*jf3.*mb.*mh;
t49 = drpy.*jh3.*mb.*mf2;
t50 = drpy.*jh3.*mb.*mh;
t51 = dmb.*jf3.*mf2.*rpy;
t52 = dmb.*jf3.*mh.*rpy;
t53 = dmb.*jh3.*mf2.*rpy;
t54 = dmb.*jh3.*mh.*rpy;
t55 = t39+t40+t42+t43+t47+t48+t49+t50+t51+t52+t53+t54;
t56 = drpz.*jf2.*mb.*mf3;
t57 = drpz.*jf2.*mb.*mh;
t58 = drpz.*jh2.*mb.*mf3;
t59 = drpz.*jh2.*mb.*mh;
t60 = dmb.*jf2.*mf3.*rpz;
t61 = dmb.*jf2.*mh.*rpz;
t62 = dmb.*jh2.*mf3.*rpz;
t63 = dmb.*jh2.*mh.*rpz;
t64 = t32+t33+t36+t37+t56+t57+t58+t59+t60+t61+t62+t63;
t65 = drpz.*jf2.*t34;
t66 = drpz.*jf2.*t35;
t67 = drpz.*jh2.*t34;
t68 = drpz.*jh2.*t35;
t69 = drpz.*jf2.*mb.*mf3.*2.0;
t70 = drpz.*jf2.*mb.*mh.*2.0;
t71 = drpz.*jh2.*mb.*mf3.*2.0;
t72 = drpz.*jh2.*mb.*mh.*2.0;
t73 = drpz.*jf2.*mf3.*mh.*2.0;
t74 = drpz.*jh2.*mf3.*mh.*2.0;
t75 = drpz.*mb.*t5.*t34;
t76 = drpz.*mb.*t5.*t35;
t77 = drpz.*mb.*mf3.*mh.*t5.*2.0;
t78 = t32+t33+t36+t37+t65+t66+t67+t68+t69+t70+t71+t72+t73+t74+t75+t76+t77-dmb.*rpz.*t5.*t34-dmb.*rpz.*t5.*t35-dmb.*mf3.*mh.*rpz.*t5.*2.0;
t79 = drpy.*jf3.*t41;
t80 = drpy.*jf3.*t35;
t81 = drpy.*jh3.*t41;
t82 = drpy.*jh3.*t35;
t83 = drpy.*jf3.*mb.*mf2.*2.0;
t84 = drpy.*jf3.*mb.*mh.*2.0;
t85 = drpy.*jh3.*mb.*mf2.*2.0;
t86 = drpy.*jh3.*mb.*mh.*2.0;
t87 = drpy.*jf3.*mf2.*mh.*2.0;
t88 = drpy.*jh3.*mf2.*mh.*2.0;
t89 = drpy.*mb.*t5.*t41;
t90 = drpy.*mb.*t5.*t35;
t91 = drpy.*mb.*mf2.*mh.*t5.*2.0;
t92 = t39+t40+t42+t43+t79+t80+t81+t82+t83+t84+t85+t86+t87+t88+t89+t90+t91-dmb.*rpy.*t5.*t35-dmb.*rpy.*t5.*t41-dmb.*mf2.*mh.*rpy.*t5.*2.0;
t93 = t15.*t92;
t94 = t5.^2;
t95 = rpy.^2;
t96 = rpz.^2;
t97 = 1.0./mp;
t98 = 1.0./t25;
t99 = 1.0./t14;
t100 = 1.0./t2;
t101 = jf2.*jf3.*mb.*t16;
t102 = jf2.*jh3.*mb.*t16;
t103 = jf3.*jh2.*mb.*t16;
t104 = jh2.*jh3.*mb.*t16;
t105 = jf2.*jf3.*mh.*t35;
t106 = jf2.*jh3.*mh.*t35;
t107 = jf3.*jh2.*mh.*t35;
t108 = jh2.*jh3.*mh.*t35;
t109 = mh.*t16.*t35.*t94;
t110 = mb.*t16.*t35.*t94;
t111 = jf2.*t5.*t16.*t35.*2.0;
t112 = jf3.*t5.*t16.*t35.*2.0;
t113 = jh2.*t5.*t16.*t35.*2.0;
t114 = jh3.*t5.*t16.*t35.*2.0;
t115 = mf1.*t16.*t35.*t94;
t116 = mf2.*t16.*t35.*t94;
t117 = mf3.*t16.*t35.*t94;
t118 = mp.*t16.*t35.*t94;
t119 = jf2.*jf3.*mf1.*t16;
t120 = jf2.*jf3.*mf2.*t16;
t121 = jf2.*jf3.*mf3.*t16;
t122 = jf2.*jf3.*mb.*t35.*3.0;
t123 = jf2.*jf3.*mh.*t16.*3.0;
t124 = jf2.*jh3.*mf1.*t16;
t125 = jf3.*jh2.*mf1.*t16;
t126 = jf2.*jh3.*mf2.*t16;
t127 = jf3.*jh2.*mf2.*t16;
t128 = jf2.*jh3.*mf3.*t16;
t129 = jf3.*jh2.*mf3.*t16;
t130 = jf2.*jh3.*mb.*t35.*3.0;
t131 = jf2.*jh3.*mh.*t16.*3.0;
t132 = jf3.*jh2.*mb.*t35.*3.0;
t133 = jf3.*jh2.*mh.*t16.*3.0;
t134 = jh2.*jh3.*mf1.*t16;
t135 = jh2.*jh3.*mf2.*t16;
t136 = jh2.*jh3.*mf3.*t16;
t137 = jh2.*jh3.*mb.*t35.*3.0;
t138 = jh2.*jh3.*mh.*t16.*3.0;
t139 = jf2.*jf3.*mf1.*t35;
t140 = jf2.*jf3.*mf2.*t35;
t141 = jf2.*jf3.*mf3.*t35;
t142 = jf2.*jh3.*mf1.*t35;
t143 = jf3.*jh2.*mf1.*t35;
t144 = jf2.*jh3.*mf2.*t35;
t145 = jf3.*jh2.*mf2.*t35;
t146 = jf2.*jh3.*mf3.*t35;
t147 = jf3.*jh2.*mf3.*t35;
t148 = jf2.*jf3.*mp.*t16;
t149 = jh2.*jh3.*mf1.*t35;
t150 = jh2.*jh3.*mf2.*t35;
t151 = jh2.*jh3.*mf3.*t35;
t152 = jf2.*jh3.*mp.*t16;
t153 = jf3.*jh2.*mp.*t16;
t154 = jh2.*jh3.*mp.*t16;
t155 = jf2.*jf3.*mp.*t35;
t156 = jf2.*jh3.*mp.*t35;
t157 = jf3.*jh2.*mp.*t35;
t158 = jh2.*jh3.*mp.*t35;
t159 = jf2.*mb.*mf2.*t5.*t16;
t160 = jf3.*mb.*mf3.*t5.*t16;
t161 = jf2.*mb.*mh.*t5.*t35;
t162 = jf2.*mb.*mh.*t5.*t16;
t163 = jf3.*mb.*mh.*t5.*t35;
t164 = jf3.*mb.*mh.*t5.*t16;
t165 = jh2.*mb.*mf2.*t5.*t16;
t166 = jh3.*mb.*mf3.*t5.*t16;
t167 = jh2.*mb.*mh.*t5.*t35;
t168 = jh2.*mb.*mh.*t5.*t16;
t169 = jh3.*mb.*mh.*t5.*t35;
t170 = jh3.*mb.*mh.*t5.*t16;
t171 = jf2.*mb.*mp.*t16.*t95;
t172 = jf3.*mb.*mp.*t16.*t96;
t173 = jh2.*mb.*mp.*t16.*t95;
t174 = jh3.*mb.*mp.*t16.*t96;
t175 = jf2.*mh.*mp.*t35.*t95;
t176 = jf3.*mh.*mp.*t35.*t96;
t177 = jh2.*mh.*mp.*t35.*t95;
t178 = jh3.*mh.*mp.*t35.*t96;
t179 = mb.*mf2.*mf3.*t16.*t94;
t180 = mb.*mf2.*mh.*t16.*t94;
t181 = mb.*mf3.*mh.*t16.*t94;
t182 = mp.*t5.*t16.*t35.*t95.*2.0;
t183 = mp.*t5.*t16.*t35.*t96.*2.0;
t184 = jf2.*mf1.*mf2.*t5.*t16;
t185 = jf2.*mf2.*mf3.*t5.*t16;
t186 = jf3.*mf1.*mf3.*t5.*t16;
t187 = jf3.*mf2.*mf3.*t5.*t16;
t188 = jf2.*mb.*mf1.*t5.*t35;
t189 = jf2.*mf1.*mh.*t5.*t16;
t190 = jf2.*mb.*mf2.*t5.*t35;
t191 = jf2.*mf2.*mh.*t5.*t16.*2.0;
t192 = jf3.*mb.*mf1.*t5.*t35;
t193 = jf3.*mf1.*mh.*t5.*t16;
t194 = jf2.*mb.*mf3.*t5.*t35;
t195 = jf2.*mf3.*mh.*t5.*t16;
t196 = jf3.*mb.*mf2.*t5.*t35;
t197 = jf3.*mf2.*mh.*t5.*t16;
t198 = jh2.*mf1.*mf2.*t5.*t16;
t199 = jf3.*mb.*mf3.*t5.*t35;
t200 = jf3.*mf3.*mh.*t5.*t16.*2.0;
t201 = jh2.*mf2.*mf3.*t5.*t16;
t202 = jh3.*mf1.*mf3.*t5.*t16;
t203 = jh3.*mf2.*mf3.*t5.*t16;
t204 = jh2.*mb.*mf1.*t5.*t35;
t205 = jh2.*mf1.*mh.*t5.*t16;
t206 = jh2.*mb.*mf2.*t5.*t35;
t207 = jh2.*mf2.*mh.*t5.*t16.*2.0;
t208 = jh3.*mb.*mf1.*t5.*t35;
t209 = jh3.*mf1.*mh.*t5.*t16;
t210 = jh2.*mb.*mf3.*t5.*t35;
t211 = jh2.*mf3.*mh.*t5.*t16;
t212 = jh3.*mb.*mf2.*t5.*t35;
t213 = jh3.*mf2.*mh.*t5.*t16;
t214 = jh3.*mb.*mf3.*t5.*t35;
t215 = jh3.*mf3.*mh.*t5.*t16.*2.0;
t216 = jf2.*mf2.*mp.*t5.*t16;
t217 = jf3.*mf3.*mp.*t5.*t16;
t218 = jf2.*mb.*mp.*t5.*t35;
t219 = jf2.*mh.*mp.*t5.*t16;
t220 = jf3.*mb.*mp.*t5.*t35;
t221 = jf3.*mh.*mp.*t5.*t16;
t222 = jh2.*mf2.*mp.*t5.*t16;
t223 = jh3.*mf3.*mp.*t5.*t16;
t224 = jh2.*mb.*mp.*t5.*t35;
t225 = jh2.*mh.*mp.*t5.*t16;
t226 = jh3.*mb.*mp.*t5.*t35;
t227 = jh3.*mh.*mp.*t5.*t16;
t228 = jf2.*mf1.*mp.*t16.*t95;
t229 = jf2.*mf2.*mp.*t16.*t95;
t230 = jf2.*mf3.*mp.*t16.*t95;
t231 = jf3.*mf1.*mp.*t16.*t96;
t232 = jf3.*mf2.*mp.*t16.*t96;
t233 = jf3.*mf3.*mp.*t16.*t96;
t234 = jf2.*mb.*mp.*t35.*t95.*3.0;
t235 = jf2.*mh.*mp.*t16.*t95.*3.0;
t236 = jh2.*mf1.*mp.*t16.*t95;
t237 = jh2.*mf2.*mp.*t16.*t95;
t238 = jh2.*mf3.*mp.*t16.*t95;
t239 = jf3.*mb.*mp.*t35.*t96.*3.0;
t240 = jf3.*mh.*mp.*t16.*t96.*3.0;
t241 = jh3.*mf1.*mp.*t16.*t96;
t242 = jh3.*mf2.*mp.*t16.*t96;
t243 = jh3.*mf3.*mp.*t16.*t96;
t244 = jh2.*mb.*mp.*t35.*t95.*3.0;
t245 = jh2.*mh.*mp.*t16.*t95.*3.0;
t246 = jh3.*mb.*mp.*t35.*t96.*3.0;
t247 = jh3.*mh.*mp.*t16.*t96.*3.0;
t248 = jf2.*mf1.*mp.*t35.*t95;
t249 = jf2.*mf2.*mp.*t35.*t95;
t250 = jf2.*mf3.*mp.*t35.*t95;
t251 = jf3.*mf1.*mp.*t35.*t96;
t252 = jf3.*mf2.*mp.*t35.*t96;
t253 = jf3.*mf3.*mp.*t35.*t96;
t254 = jh2.*mf1.*mp.*t35.*t95;
t255 = jh2.*mf2.*mp.*t35.*t95;
t256 = jh2.*mf3.*mp.*t35.*t95;
t257 = jh3.*mf1.*mp.*t35.*t96;
t258 = jh3.*mf2.*mp.*t35.*t96;
t259 = jh3.*mf3.*mp.*t35.*t96;
t260 = mf1.*mf2.*mf3.*t16.*t94;
t261 = mf1.*mf2.*mh.*t16.*t94;
t262 = mf1.*mf3.*mh.*t16.*t94;
t263 = mf2.*mf3.*mh.*t16.*t94;
t264 = mf2.*mf3.*mp.*t16.*t94;
t265 = mf2.*mh.*mp.*t16.*t94;
t266 = mf3.*mh.*mp.*t16.*t94;
t267 = jf2.*jf3.*mb.*mf1.*mf2;
t268 = jf2.*jf3.*mb.*mf1.*mf3;
t269 = jf2.*jf3.*mb.*mf2.*mf3;
t270 = jf2.*jf3.*mb.*mf1.*mh.*2.0;
t271 = jf2.*jf3.*mb.*mf2.*mh.*2.0;
t272 = jf2.*jf3.*mb.*mf3.*mh.*2.0;
t273 = jf2.*jh3.*mb.*mf1.*mf2;
t274 = jf3.*jh2.*mb.*mf1.*mf2;
t275 = jf2.*jh3.*mb.*mf1.*mf3;
t276 = jf3.*jh2.*mb.*mf1.*mf3;
t277 = jf2.*jh3.*mb.*mf2.*mf3;
t278 = jf3.*jh2.*mb.*mf2.*mf3;
t279 = jf2.*jh3.*mb.*mf1.*mh.*2.0;
t280 = jf3.*jh2.*mb.*mf1.*mh.*2.0;
t281 = jf2.*jh3.*mb.*mf2.*mh.*2.0;
t282 = jf3.*jh2.*mb.*mf2.*mh.*2.0;
t283 = jf2.*jh3.*mb.*mf3.*mh.*2.0;
t284 = jf3.*jh2.*mb.*mf3.*mh.*2.0;
t285 = jh2.*jh3.*mb.*mf1.*mf2;
t286 = jh2.*jh3.*mb.*mf1.*mf3;
t287 = jh2.*jh3.*mb.*mf2.*mf3;
t288 = jf2.*jf3.*mf1.*mf2.*mf3;
t289 = jh2.*jh3.*mb.*mf1.*mh.*2.0;
t290 = jh2.*jh3.*mb.*mf2.*mh.*2.0;
t291 = jf2.*jf3.*mf1.*mf2.*mh;
t292 = jh2.*jh3.*mb.*mf3.*mh.*2.0;
t293 = jf2.*jf3.*mf1.*mf3.*mh;
t294 = jf2.*jf3.*mf2.*mf3.*mh;
t295 = jf2.*jh3.*mf1.*mf2.*mf3;
t296 = jf3.*jh2.*mf1.*mf2.*mf3;
t297 = jf2.*jh3.*mf1.*mf2.*mh;
t298 = jf3.*jh2.*mf1.*mf2.*mh;
t299 = jf2.*jh3.*mf1.*mf3.*mh;
t300 = jf3.*jh2.*mf1.*mf3.*mh;
t301 = jf2.*jh3.*mf2.*mf3.*mh;
t302 = jf3.*jh2.*mf2.*mf3.*mh;
t303 = jh2.*jh3.*mf1.*mf2.*mf3;
t304 = jf2.*jf3.*mb.*mf2.*mp;
t305 = jf2.*jf3.*mb.*mf3.*mp;
t306 = jh2.*jh3.*mf1.*mf2.*mh;
t307 = jh2.*jh3.*mf1.*mf3.*mh;
t308 = jh2.*jh3.*mf2.*mf3.*mh;
t309 = jf2.*jf3.*mb.*mh.*mp.*2.0;
t310 = jf2.*jh3.*mb.*mf2.*mp;
t311 = jf3.*jh2.*mb.*mf2.*mp;
t312 = jf2.*jh3.*mb.*mf3.*mp;
t313 = jf3.*jh2.*mb.*mf3.*mp;
t314 = jf2.*jh3.*mb.*mh.*mp.*2.0;
t315 = jf3.*jh2.*mb.*mh.*mp.*2.0;
t316 = jh2.*jh3.*mb.*mf2.*mp;
t317 = jh2.*jh3.*mb.*mf3.*mp;
t318 = jf2.*jf3.*mf2.*mf3.*mp;
t319 = jh2.*jh3.*mb.*mh.*mp.*2.0;
t320 = jf2.*jf3.*mf2.*mh.*mp;
t321 = jf2.*jf3.*mf3.*mh.*mp;
t322 = jf2.*jh3.*mf2.*mf3.*mp;
t323 = jf3.*jh2.*mf2.*mf3.*mp;
t324 = jf2.*jh3.*mf2.*mh.*mp;
t325 = jf3.*jh2.*mf2.*mh.*mp;
t326 = jf2.*jh3.*mf3.*mh.*mp;
t327 = jf3.*jh2.*mf3.*mh.*mp;
t328 = jh2.*jh3.*mf2.*mf3.*mp;
t329 = jh2.*jh3.*mf2.*mh.*mp;
t330 = jh2.*jh3.*mf3.*mh.*mp;
t331 = mb.*mf3.*mp.*t5.*t16.*t95;
t332 = mb.*mf2.*mp.*t5.*t16.*t96;
t333 = mb.*mh.*mp.*t5.*t35.*t95;
t334 = mb.*mh.*mp.*t5.*t16.*t95;
t335 = mb.*mh.*mp.*t5.*t35.*t96;
t336 = mb.*mh.*mp.*t5.*t16.*t96;
t337 = mf1.*mf3.*mp.*t5.*t16.*t95;
t338 = mf2.*mf3.*mp.*t5.*t16.*t95;
t339 = mf1.*mf2.*mp.*t5.*t16.*t96;
t340 = mf2.*mf3.*mp.*t5.*t16.*t96;
t341 = mb.*mf1.*mp.*t5.*t35.*t95;
t342 = mf1.*mh.*mp.*t5.*t16.*t95;
t343 = mb.*mf2.*mp.*t5.*t35.*t95;
t344 = mf2.*mh.*mp.*t5.*t16.*t95;
t345 = mb.*mf3.*mp.*t5.*t35.*t95;
t346 = mf3.*mh.*mp.*t5.*t16.*t95.*2.0;
t347 = mb.*mf1.*mp.*t5.*t35.*t96;
t348 = mf1.*mh.*mp.*t5.*t16.*t96;
t349 = mb.*mf2.*mp.*t5.*t35.*t96;
t350 = mf2.*mh.*mp.*t5.*t16.*t96.*2.0;
t351 = mb.*mf3.*mp.*t5.*t35.*t96;
t352 = mf3.*mh.*mp.*t5.*t16.*t96;
t353 = jf2.*mb.*mf1.*mf2.*mf3.*t5;
t354 = jf3.*mb.*mf1.*mf2.*mf3.*t5;
t355 = jf2.*mb.*mf1.*mf2.*mh.*t5;
t356 = jf2.*mb.*mf1.*mf3.*mh.*t5;
t357 = jf3.*mb.*mf1.*mf2.*mh.*t5;
t358 = jf2.*mb.*mf2.*mf3.*mh.*t5;
t359 = jf3.*mb.*mf1.*mf3.*mh.*t5;
t360 = jf3.*mb.*mf2.*mf3.*mh.*t5;
t361 = jh2.*mb.*mf1.*mf2.*mf3.*t5;
t362 = jh3.*mb.*mf1.*mf2.*mf3.*t5;
t363 = jh2.*mb.*mf1.*mf2.*mh.*t5;
t364 = jh2.*mb.*mf1.*mf3.*mh.*t5;
t365 = jh3.*mb.*mf1.*mf2.*mh.*t5;
t366 = jh2.*mb.*mf2.*mf3.*mh.*t5;
t367 = jh3.*mb.*mf1.*mf3.*mh.*t5;
t368 = jh3.*mb.*mf2.*mf3.*mh.*t5;
t369 = jf2.*mb.*mf2.*mf3.*mp.*t5;
t370 = jf3.*mb.*mf2.*mf3.*mp.*t5;
t371 = jf2.*mb.*mf2.*mh.*mp.*t5;
t372 = jf2.*mb.*mf3.*mh.*mp.*t5;
t373 = jf3.*mb.*mf2.*mh.*mp.*t5;
t374 = jf3.*mb.*mf3.*mh.*mp.*t5;
t375 = jh2.*mb.*mf2.*mf3.*mp.*t5;
t376 = jh3.*mb.*mf2.*mf3.*mp.*t5;
t377 = jh2.*mb.*mf2.*mh.*mp.*t5;
t378 = jh2.*mb.*mf3.*mh.*mp.*t5;
t379 = jh3.*mb.*mf2.*mh.*mp.*t5;
t380 = jh3.*mb.*mf3.*mh.*mp.*t5;
t381 = jf2.*mb.*mf1.*mf2.*mp.*t95;
t382 = jf2.*mb.*mf1.*mf3.*mp.*t95;
t383 = jf2.*mb.*mf2.*mf3.*mp.*t95;
t384 = jf3.*mb.*mf1.*mf2.*mp.*t96;
t385 = jf3.*mb.*mf1.*mf3.*mp.*t96;
t386 = jf3.*mb.*mf2.*mf3.*mp.*t96;
t387 = jf2.*mb.*mf1.*mh.*mp.*t95.*2.0;
t388 = jf2.*mb.*mf2.*mh.*mp.*t95.*2.0;
t389 = jf2.*mb.*mf3.*mh.*mp.*t95.*2.0;
t390 = jh2.*mb.*mf1.*mf2.*mp.*t95;
t391 = jh2.*mb.*mf1.*mf3.*mp.*t95;
t392 = jh2.*mb.*mf2.*mf3.*mp.*t95;
t393 = jf3.*mb.*mf1.*mh.*mp.*t96.*2.0;
t394 = jf3.*mb.*mf2.*mh.*mp.*t96.*2.0;
t395 = jf3.*mb.*mf3.*mh.*mp.*t96.*2.0;
t396 = jh3.*mb.*mf1.*mf2.*mp.*t96;
t397 = jh3.*mb.*mf1.*mf3.*mp.*t96;
t398 = jh3.*mb.*mf2.*mf3.*mp.*t96;
t399 = jh2.*mb.*mf1.*mh.*mp.*t95.*2.0;
t400 = jh2.*mb.*mf2.*mh.*mp.*t95.*2.0;
t401 = jh2.*mb.*mf3.*mh.*mp.*t95.*2.0;
t402 = jf2.*mf1.*mf2.*mf3.*mp.*t95;
t403 = jh3.*mb.*mf1.*mh.*mp.*t96.*2.0;
t404 = jh3.*mb.*mf2.*mh.*mp.*t96.*2.0;
t405 = jh3.*mb.*mf3.*mh.*mp.*t96.*2.0;
t406 = jf3.*mf1.*mf2.*mf3.*mp.*t96;
t407 = jf2.*mf1.*mf2.*mh.*mp.*t95;
t408 = jf2.*mf1.*mf3.*mh.*mp.*t95;
t409 = jf2.*mf2.*mf3.*mh.*mp.*t95;
t410 = jh2.*mf1.*mf2.*mf3.*mp.*t95;
t411 = jf3.*mf1.*mf2.*mh.*mp.*t96;
t412 = jf3.*mf1.*mf3.*mh.*mp.*t96;
t413 = jf3.*mf2.*mf3.*mh.*mp.*t96;
t414 = jh3.*mf1.*mf2.*mf3.*mp.*t96;
t415 = jh2.*mf1.*mf2.*mh.*mp.*t95;
t416 = jh2.*mf1.*mf3.*mh.*mp.*t95;
t417 = jh2.*mf2.*mf3.*mh.*mp.*t95;
t418 = jh3.*mf1.*mf2.*mh.*mp.*t96;
t419 = jh3.*mf1.*mf3.*mh.*mp.*t96;
t420 = jh3.*mf2.*mf3.*mh.*mp.*t96;
t421 = mb.*mf1.*mf2.*mf3.*mp.*t5.*t95;
t422 = mb.*mf1.*mf2.*mf3.*mp.*t5.*t96;
t423 = mb.*mf1.*mf2.*mh.*mp.*t5.*t95;
t424 = mb.*mf1.*mf3.*mh.*mp.*t5.*t95;
t425 = mb.*mf2.*mf3.*mh.*mp.*t5.*t95;
t426 = mb.*mf1.*mf2.*mh.*mp.*t5.*t96;
t427 = mb.*mf1.*mf3.*mh.*mp.*t5.*t96;
t428 = mb.*mf2.*mf3.*mh.*mp.*t5.*t96;
t429 = t101+t102+t103+t104+t105+t106+t107+t108+t109+t110+t111+t112+t113+t114+t115+t116+t117+t118+t119+t120+t121+t122+t123+t124+t125+t126+t127+t128+t129+t130+t131+t132+t133+t134+t135+t136+t137+t138+t139+t140+t141+t142+t143+t144+t145+t146+t147+t148+t149+t150+t151+t152+t153+t154+t155+t156+t157+t158+t159+t160+t161+t162+t163+t164+t165+t166+t167+t168+t169+t170+t171+t172+t173+t174+t175+t176+t177+t178+t179+t180+t181+t182+t183+t184+t185+t186+t187+t188+t189+t190+t191+t192+t193+t194+t195+t196+t197+t198+t199+t200+t201+t202+t203+t204+t205+t206+t207+t208+t209+t210+t211+t212+t213+t214+t215+t216+t217+t218+t219+t220+t221+t222+t223+t224+t225+t226+t227+t228+t229+t230+t231+t232+t233+t234+t235+t236+t237+t238+t239+t240+t241+t242+t243+t244+t245+t246+t247+t248+t249+t250+t251+t252+t253+t254+t255+t256+t257+t258+t259+t260+t261+t262+t263+t264+t265+t266+t267+t268+t269+t270+t271+t272+t273+t274+t275+t276+t277+t278+t279+t280+t281+t282+t283+t284+t285+t286+t287+t288+t289+t290+t291+t292+t293+t294+t295+t296+t297+t298+t299+t300+t301+t302+t303+t304+t305+t306+t307+t308+t309+t310+t311+t312+t313+t314+t315+t316+t317+t318+t319+t320+t321+t322+t323+t324+t325+t326+t327+t328+t329+t330+t331+t332+t333+t334+t335+t336+t337+t338+t339+t340+t341+t342+t343+t344+t345+t346+t347+t348+t349+t350+t351+t352+t353+t354+t355+t356+t357+t358+t359+t360+t361+t362+t363+t364+t365+t366+t367+t368+t369+t370+t371+t372+t373+t374+t375+t376+t377+t378+t379+t380+t381+t382+t383+t384+t385+t386+t387+t388+t389+t390+t391+t392+t393+t394+t395+t396+t397+t398+t399+t400+t401+t402+t403+t404+t405+t406+t407+t408+t409+t410+t411+t412+t413+t414+t415+t416+t417+t418+t419+t420+t421+t422+t423+t424+t425+t426+t427+t428;
t430 = mh.*t5;
t431 = mb+mf2+mh;
t432 = mb.*rpx;
t433 = mh.*rpx;
t434 = mb+mf3+mh;
t435 = mh.*rbx.*rpx;
t436 = jf3.^2;
t437 = dmb.*t436;
t438 = jh3.^2;
t439 = dmb.*t438;
t440 = dmb.*jf3.*jh3.*2.0;
t441 = drpx.*jf3.*rbx.*t16;
t442 = drpx.*jh3.*rbx.*t16;
t443 = drpx.*mf2.*rbx.*t5.*t16;
t444 = drpx.*jf3.*mb.*mf2.*rbx;
t445 = drpx.*jf3.*mb.*mh.*rbx;
t446 = drpx.*jh3.*mb.*mf2.*rbx;
t447 = drpx.*jh3.*mb.*mh.*rbx;
t448 = dmb.*jf3.*mf2.*rbx.*rpx;
t449 = dmb.*jf3.*mh.*rbx.*rpx;
t450 = dmb.*jh3.*mf2.*rbx.*rpx;
t451 = dmb.*jh3.*mh.*rbx.*rpx;
t452 = t27+t437+t439+t440+t441+t442+t443+t444+t445+t446+t447+t448+t449+t450+t451;
t453 = t15.*t452;
t454 = drpz.*t29;
t455 = drpx.*jf3.*t16;
t456 = drpx.*jh3.*t16;
t457 = drpx.*jf3.*t41;
t458 = drpx.*jf3.*t35;
t459 = drpx.*jh3.*t41;
t460 = drpx.*jh3.*t35;
t461 = drpx.*jf3.*mb.*mf2.*2.0;
t462 = drpx.*jf3.*mb.*mh.*2.0;
t463 = drpx.*jh3.*mb.*mf2.*2.0;
t464 = drpx.*jh3.*mb.*mh.*2.0;
t465 = drpx.*jf3.*mf2.*mh.*2.0;
t466 = drpx.*jh3.*mf2.*mh.*2.0;
t467 = drpx.*mb.*t5.*t41;
t468 = drpx.*mf2.*t5.*t16;
t469 = drpx.*mb.*mf2.*mh.*t5.*2.0;
t510 = dmb.*rpx.*t5.*t35;
t470 = t44+t45+t455+t456+t457+t458+t459+t460+t461+t462+t463+t464+t465+t466+t467+t468+t469-t510-dmb.*jf3.*mf2.*rbx-dmb.*jf3.*mh.*rbx-dmb.*jh3.*mf2.*rbx-dmb.*jh3.*mh.*rbx-dmb.*rpx.*t5.*t41-dmb.*mf2.*mh.*rpx.*t5.*2.0;
t471 = mf2.*rpx;
t477 = mb.*rbx;
t472 = t432+t433+t471-t477;
t473 = mf2.*rbx.*rpx;
t474 = jf3+jh3+t435+t473;
t475 = dmb.*rbx.*rpy.*t15.*t38.*t474;
t476 = t475-drpy.*t99.*t472-drpx.*rpy.*t99.*t431;
t478 = jf2.^2;
t479 = dmb.*t478;
t480 = jh2.^2;
t481 = dmb.*t480;
t482 = dmb.*jf2.*jh2.*2.0;
t483 = drpx.*jf2.*rbx.*t16;
t484 = drpx.*jh2.*rbx.*t16;
t485 = drpx.*mf3.*rbx.*t5.*t16;
t486 = drpx.*jf2.*mb.*mf3.*rbx;
t487 = drpx.*jf2.*mb.*mh.*rbx;
t488 = drpx.*jh2.*mb.*mf3.*rbx;
t489 = drpx.*jh2.*mb.*mh.*rbx;
t490 = dmb.*jf2.*mf3.*rbx.*rpx;
t491 = dmb.*jf2.*mh.*rbx.*rpx;
t492 = dmb.*jh2.*mf3.*rbx.*rpx;
t493 = dmb.*jh2.*mh.*rbx.*rpx;
t494 = t27+t479+t481+t482+t483+t484+t485+t486+t487+t488+t489+t490+t491+t492+t493;
t495 = t26.*t494;
t496 = drpx.*jf2.*t16;
t497 = drpx.*jh2.*t16;
t498 = drpx.*jf2.*t34;
t499 = drpx.*jf2.*t35;
t500 = drpx.*jh2.*t34;
t501 = drpx.*jh2.*t35;
t502 = drpx.*jf2.*mb.*mf3.*2.0;
t503 = drpx.*jf2.*mb.*mh.*2.0;
t504 = drpx.*jh2.*mb.*mf3.*2.0;
t505 = drpx.*jh2.*mb.*mh.*2.0;
t506 = drpx.*jf2.*mf3.*mh.*2.0;
t507 = drpx.*jh2.*mf3.*mh.*2.0;
t508 = drpx.*mb.*t5.*t34;
t509 = drpx.*mf3.*t5.*t16;
t511 = drpx.*mb.*mf3.*mh.*t5.*2.0;
t512 = mf3.*rpx;
t513 = mf3.*rbx.*rpx;
t514 = jf2+jh2+t435+t513;
t515 = dmb.*rbx.*rpz.*t26.*t30.*t514;
t516 = drpz.*rpy;
t517 = drpy.*rpz;
t518 = t516+t517;
t519 = t432+t433-t477+t512;
dIinv = reshape([-dmb.*t3,0.0,0.0,0.0,0.0,0.0,t46,0.0,0.0,0.0,-dmb.*t4.^2.*t15,0.0,0.0,0.0,-dmb.*rbx.*t4.*t15.*t38,-rbx.*t15.*t55,t453,0.0,0.0,0.0,-dmb.*t17.^2.*t26,0.0,t31,0.0,-rbx.*t26.*t64,0.0,t495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t454,-drpy.*t29,0.0,0.0,t31,0.0,-dmb.*t5.*t26.*t30.^2,0.0,-t26.*t78,0.0,t26.*(t44+t45+t496+t497+t498+t499+t500+t501+t502+t503+t504+t505+t506+t507+t508+t509-t510+t511-dmb.*jf2.*mf3.*rbx-dmb.*jf2.*mh.*rbx-dmb.*jh2.*mf3.*rbx-dmb.*jh2.*mh.*rbx-dmb.*rpx.*t5.*t34-dmb.*mf3.*mh.*rpx.*t5.*2.0),0.0,-dmb.*rbx.*t4.*t15.*t38,0.0,0.0,0.0,-dmb.*t5.*t15.*t38.^2,t93,-t15.*t470,0.0,t46,-rbx.*t15.*t55,-rbx.*t26.*t64,0.0,-t26.*t78,t93,-dmb.*(t3.*t97.*t98.*t99.*t429-t97.*t98.*t99.*t100.*(jf2.*jf3.*t16.*3.0+jf2.*jf3.*t35.*3.0+jf2.*jh3.*t16.*3.0+jf3.*jh2.*t16.*3.0+jf2.*jh3.*t35.*3.0+jf3.*jh2.*t35.*3.0+jh2.*jh3.*t16.*3.0+jh2.*jh3.*t35.*3.0+t16.*t35.*t94.*3.0+jf2.*jf3.*mb.*mf1.*2.0+jf2.*jf3.*mb.*mf2.*2.0+jf2.*jf3.*mb.*mf3.*2.0+jf2.*jf3.*mb.*mh.*6.0+jf2.*jh3.*mb.*mf1.*2.0+jf3.*jh2.*mb.*mf1.*2.0+jf2.*jh3.*mb.*mf2.*2.0+jf3.*jh2.*mb.*mf2.*2.0+jf2.*jh3.*mb.*mf3.*2.0+jf3.*jh2.*mb.*mf3.*2.0+jf2.*jh3.*mb.*mh.*6.0+jf3.*jh2.*mb.*mh.*6.0+jh2.*jh3.*mb.*mf1.*2.0+jh2.*jh3.*mb.*mf2.*2.0+jf2.*jf3.*mf1.*mf2+jh2.*jh3.*mb.*mf3.*2.0+jf2.*jf3.*mf1.*mf3+jf2.*jf3.*mf2.*mf3+jh2.*jh3.*mb.*mh.*6.0+jf2.*jf3.*mf1.*mh.*2.0+jf2.*jf3.*mf2.*mh.*2.0+jf2.*jf3.*mf3.*mh.*2.0+jf2.*jh3.*mf1.*mf2+jf3.*jh2.*mf1.*mf2+jf2.*jh3.*mf1.*mf3+jf3.*jh2.*mf1.*mf3+jf2.*jh3.*mf2.*mf3+jf3.*jh2.*mf2.*mf3+jf2.*jh3.*mf1.*mh.*2.0+jf3.*jh2.*mf1.*mh.*2.0+jf2.*jh3.*mf2.*mh.*2.0+jf3.*jh2.*mf2.*mh.*2.0+jf2.*jh3.*mf3.*mh.*2.0+jf3.*jh2.*mf3.*mh.*2.0+jh2.*jh3.*mf1.*mf2+jh2.*jh3.*mf1.*mf3+jh2.*jh3.*mf2.*mf3+jf2.*jf3.*mb.*mp.*2.0+jh2.*jh3.*mf1.*mh.*2.0+jh2.*jh3.*mf2.*mh.*2.0+jh2.*jh3.*mf3.*mh.*2.0+jf2.*jh3.*mb.*mp.*2.0+jf3.*jh2.*mb.*mp.*2.0+jh2.*jh3.*mb.*mp.*2.0+jf2.*jf3.*mf2.*mp+jf2.*jf3.*mf3.*mp+jf2.*jf3.*mh.*mp.*2.0+jf2.*jh3.*mf2.*mp+jf3.*jh2.*mf2.*mp+jf2.*jh3.*mf3.*mp+jf3.*jh2.*mf3.*mp+jf2.*jh3.*mh.*mp.*2.0+jf3.*jh2.*mh.*mp.*2.0+jh2.*jh3.*mf2.*mp+jh2.*jh3.*mf3.*mp+jh2.*jh3.*mh.*mp.*2.0+jf2.*mb.*t5.*t35.*4.0+jf3.*mb.*t5.*t35.*4.0+jh2.*mb.*t5.*t35.*4.0+jh3.*mb.*t5.*t35.*4.0+jf2.*mf2.*t5.*t16.*3.0+jf3.*mf3.*t5.*t16.*3.0+jf2.*mf1.*t5.*t35+jf2.*mf2.*t5.*t35+jf3.*mf1.*t5.*t35+jf2.*mf3.*t5.*t35+jf3.*mf2.*t5.*t35+jf3.*mf3.*t5.*t35+jf2.*mh.*t5.*t16.*3.0+jf3.*mh.*t5.*t16.*3.0+jh2.*mf2.*t5.*t16.*3.0+jh3.*mf3.*t5.*t16.*3.0+jf2.*mh.*t5.*t35+jf3.*mh.*t5.*t35+jh2.*mf1.*t5.*t35+jh2.*mf2.*t5.*t35+jh3.*mf1.*t5.*t35+jh2.*mf3.*t5.*t35+jh3.*mf2.*t5.*t35+jh3.*mf3.*t5.*t35+jh2.*mh.*t5.*t16.*3.0+jh3.*mh.*t5.*t16.*3.0+jh2.*mh.*t5.*t35+jh3.*mh.*t5.*t35+jf2.*mp.*t5.*t35+jf3.*mp.*t5.*t35+jf2.*mp.*t16.*t95.*3.0+jf3.*mp.*t16.*t96.*3.0+jf2.*mp.*t35.*t95.*3.0+jf3.*mp.*t35.*t96.*3.0+jh2.*mp.*t5.*t35+jh3.*mp.*t5.*t35+jh2.*mp.*t16.*t95.*3.0+jh3.*mp.*t16.*t96.*3.0+jh2.*mp.*t35.*t95.*3.0+jh3.*mp.*t35.*t96.*3.0+mb.*mf1.*t35.*t94.*2.0+mb.*mf2.*t35.*t94.*2.0+mb.*mf3.*t35.*t94.*2.0+mb.*mh.*t35.*t94.*2.0+mf2.*mf3.*t16.*t94.*3.0+mf2.*mh.*t16.*t94.*3.0+mf3.*mh.*t16.*t94.*3.0+mb.*mp.*t35.*t94.*2.0+jf2.*mb.*mf1.*mf2.*t5.*2.0+jf2.*mb.*mf2.*mf3.*t5.*2.0+jf3.*mb.*mf1.*mf3.*t5.*2.0+jf3.*mb.*mf2.*mf3.*t5.*2.0+jf2.*mb.*mf1.*mh.*t5.*2.0+jf2.*mb.*mf2.*mh.*t5.*4.0+jf3.*mb.*mf1.*mh.*t5.*2.0+jf2.*mb.*mf3.*mh.*t5.*2.0+jf3.*mb.*mf2.*mh.*t5.*2.0+jh2.*mb.*mf1.*mf2.*t5.*2.0+jf3.*mb.*mf3.*mh.*t5.*4.0+jh2.*mb.*mf2.*mf3.*t5.*2.0+jh3.*mb.*mf1.*mf3.*t5.*2.0+jh3.*mb.*mf2.*mf3.*t5.*2.0+jh2.*mb.*mf1.*mh.*t5.*2.0+jh2.*mb.*mf2.*mh.*t5.*4.0+jh3.*mb.*mf1.*mh.*t5.*2.0+jh2.*mb.*mf3.*mh.*t5.*2.0+jh3.*mb.*mf2.*mh.*t5.*2.0+jh3.*mb.*mf3.*mh.*t5.*4.0+jf2.*mf1.*mf2.*mf3.*t5+jf3.*mf1.*mf2.*mf3.*t5+jf2.*mf1.*mf2.*mh.*t5+jf2.*mf1.*mf3.*mh.*t5+jf3.*mf1.*mf2.*mh.*t5+jf2.*mf2.*mf3.*mh.*t5+jf3.*mf1.*mf3.*mh.*t5+jf3.*mf2.*mf3.*mh.*t5+jh2.*mf1.*mf2.*mf3.*t5+jh3.*mf1.*mf2.*mf3.*t5+jh2.*mf1.*mf2.*mh.*t5+jh2.*mf1.*mf3.*mh.*t5+jh3.*mf1.*mf2.*mh.*t5+jh2.*mf2.*mf3.*mh.*t5+jh3.*mf1.*mf3.*mh.*t5+jh3.*mf2.*mf3.*mh.*t5+jf2.*mb.*mf2.*mp.*t5.*2.0+jf3.*mb.*mf3.*mp.*t5.*2.0+jf2.*mb.*mf1.*mp.*t95.*2.0+jf2.*mb.*mf2.*mp.*t95.*2.0+jf2.*mb.*mf3.*mp.*t95.*2.0+jf3.*mb.*mf1.*mp.*t96.*2.0+jf3.*mb.*mf2.*mp.*t96.*2.0+jf3.*mb.*mf3.*mp.*t96.*2.0+jf2.*mb.*mh.*mp.*t5.*2.0+jf3.*mb.*mh.*mp.*t5.*2.0+jh2.*mb.*mf2.*mp.*t5.*2.0+jh3.*mb.*mf3.*mp.*t5.*2.0+jf2.*mb.*mh.*mp.*t95.*6.0+jh2.*mb.*mf1.*mp.*t95.*2.0+jf3.*mb.*mh.*mp.*t96.*6.0+jh2.*mb.*mf2.*mp.*t95.*2.0+jh2.*mb.*mf3.*mp.*t95.*2.0+jh3.*mb.*mf1.*mp.*t96.*2.0+jh3.*mb.*mf2.*mp.*t96.*2.0+jh3.*mb.*mf3.*mp.*t96.*2.0+jh2.*mb.*mh.*mp.*t5.*2.0+jh3.*mb.*mh.*mp.*t5.*2.0+jf2.*mf2.*mf3.*mp.*t5+jf3.*mf2.*mf3.*mp.*t5+jh2.*mb.*mh.*mp.*t95.*6.0+jh3.*mb.*mh.*mp.*t96.*6.0+jf2.*mf1.*mf2.*mp.*t95+jf2.*mf1.*mf3.*mp.*t95+jf2.*mf2.*mf3.*mp.*t95+jf3.*mf1.*mf2.*mp.*t96+jf3.*mf1.*mf3.*mp.*t96+jf3.*mf2.*mf3.*mp.*t96+jf2.*mf2.*mh.*mp.*t5+jf2.*mf3.*mh.*mp.*t5+jf3.*mf2.*mh.*mp.*t5+jf3.*mf3.*mh.*mp.*t5+jh2.*mf2.*mf3.*mp.*t5+jh3.*mf2.*mf3.*mp.*t5+jf2.*mf1.*mh.*mp.*t95.*2.0+jf2.*mf2.*mh.*mp.*t95.*2.0+jf2.*mf3.*mh.*mp.*t95.*2.0+jf3.*mf1.*mh.*mp.*t96.*2.0+jh2.*mf1.*mf2.*mp.*t95+jf3.*mf2.*mh.*mp.*t96.*2.0+jh2.*mf1.*mf3.*mp.*t95+jf3.*mf3.*mh.*mp.*t96.*2.0+jh2.*mf2.*mf3.*mp.*t95+jh3.*mf1.*mf2.*mp.*t96+jh3.*mf1.*mf3.*mp.*t96+jh3.*mf2.*mf3.*mp.*t96+jh2.*mf2.*mh.*mp.*t5+jh2.*mf3.*mh.*mp.*t5+jh3.*mf2.*mh.*mp.*t5+jh3.*mf3.*mh.*mp.*t5+jh2.*mf1.*mh.*mp.*t95.*2.0+jh2.*mf2.*mh.*mp.*t95.*2.0+jh2.*mf3.*mh.*mp.*t95.*2.0+jh3.*mf1.*mh.*mp.*t96.*2.0+jh3.*mf2.*mh.*mp.*t96.*2.0+jh3.*mf3.*mh.*mp.*t96.*2.0+mb.*mf1.*mf2.*mf3.*t94.*2.0+mb.*mf1.*mf2.*mh.*t94.*2.0+mb.*mf1.*mf3.*mh.*t94.*2.0+mb.*mf2.*mf3.*mh.*t94.*2.0+mb.*mf2.*mf3.*mp.*t94.*2.0+mb.*mf2.*mh.*mp.*t94.*2.0+mb.*mf3.*mh.*mp.*t94.*2.0+mb.*mp.*t5.*t35.*t95.*4.0+mb.*mp.*t5.*t35.*t96.*4.0+mf2.*mp.*t5.*t16.*t96.*3.0+mf3.*mp.*t5.*t16.*t95.*3.0+mf1.*mp.*t5.*t35.*t95+mf1.*mp.*t5.*t35.*t96+mf2.*mp.*t5.*t35.*t95+mf2.*mp.*t5.*t35.*t96+mf3.*mp.*t5.*t35.*t95+mf3.*mp.*t5.*t35.*t96+mh.*mp.*t5.*t16.*t95.*3.0+mh.*mp.*t5.*t16.*t96.*3.0+mh.*mp.*t5.*t35.*t95+mh.*mp.*t5.*t35.*t96+mb.*mf1.*mf2.*mp.*t5.*t96.*2.0+mb.*mf1.*mf3.*mp.*t5.*t95.*2.0+mb.*mf2.*mf3.*mp.*t5.*t95.*2.0+mb.*mf2.*mf3.*mp.*t5.*t96.*2.0+mb.*mf1.*mh.*mp.*t5.*t95.*2.0+mb.*mf1.*mh.*mp.*t5.*t96.*2.0+mb.*mf2.*mh.*mp.*t5.*t95.*2.0+mb.*mf2.*mh.*mp.*t5.*t96.*4.0+mb.*mf3.*mh.*mp.*t5.*t95.*4.0+mb.*mf3.*mh.*mp.*t5.*t96.*2.0+mf1.*mf2.*mf3.*mp.*t5.*t95+mf1.*mf2.*mf3.*mp.*t5.*t96+mf1.*mf2.*mh.*mp.*t5.*t95+mf1.*mf2.*mh.*mp.*t5.*t96+mf1.*mf3.*mh.*mp.*t5.*t95+mf1.*mf3.*mh.*mp.*t5.*t96+mf2.*mf3.*mh.*mp.*t5.*t95+mf2.*mf3.*mh.*mp.*t5.*t96)+t15.*t97.*t98.*t100.*t429.*(jf3+jh3+t430+mf2.*t5)+t26.*t97.*t99.*t100.*t429.*(jf2+jh2+t430+mf3.*t5))+drpy.*rpy.*t99.*t431.*2.0+drpz.*rpz.*t98.*t434.*2.0,t476,t515-drpz.*t98.*t519-drpx.*rpz.*t98.*t434,0.0,t453,0.0,t454,0.0,-t15.*t470,t476,-dmb.*t15.*t474.^2+drpz.*rpz.*t29.*2.0+drpx.*t99.*t472.*2.0,-t29.*t518,0.0,0.0,t495,-drpy.*t29,t26.*(t44+t45+t496+t497+t498+t499+t500+t501+t502+t503+t504+t505+t506+t507+t508+t509+t511-dmb.*jf2.*mf3.*rbx-dmb.*jf2.*mh.*rbx-dmb.*jh2.*mf3.*rbx-dmb.*jh2.*mh.*rbx-dmb.*rpx.*t5.*t34-dmb.*rpx.*t5.*t35-dmb.*mf3.*mh.*rpx.*t5.*2.0),0.0,t515-drpz.*t98.*(t432+t433+t512-mb.*rbx)-drpx.*rpz.*t98.*t434,-t29.*t518,-dmb.*t26.*t514.^2+drpy.*rpy.*t29.*2.0+drpx.*t98.*t519.*2.0],[9,9]);
end

function Finv  =  Calculate_Finv(Iinv)
F=Iinv(7:9,7:9);
Finv=inv(F);
end

function R = Calculate_R(ph,tet,ps)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here

R=[cos(ps)*cos(tet),-sin(ps)*cos(ph)+cos(ps)*sin(tet)*sin(ph),sin(ps)*sin(ph)+cos(ps)*sin(tet)*cos(ph);
   sin(ps)*cos(tet),cos(ps)*cos(ph)+sin(ps)*sin(tet)*sin(ph),-cos(ps)*sin(ph)+sin(ps)*sin(tet)*cos(ph);
   -sin(tet),cos(tet)*sin(ph),cos(tet)*cos(ph)];


end

function Rwb = Calculate_Rwb(alpha,beta)

Rwb=[cos(alpha)*cos(beta),-cos(alpha)*sin(beta),-sin(alpha);
    sin(beta),cos(beta),0;
    sin(alpha)*cos(beta),-sin(alpha)*sin(beta),cos(alpha)];
end

function [F,M] = Calculate_F_M(R,Rwb,mv,m,g,rcg,alpha,beta,kd0,kd,kl0,kl,km0,km,k1,k2,v,w)
fg_i=mv*g*[0;0;1];
fb_i=m*g*[0;0;-1];
Fg=R'*fg_i;
Fb=R'*fb_i;
Mg=cross(rcg,Fg);

D=Calculate_D(alpha,beta,v,kd0,kd);
Fd=Rwb*D;

L=Calculate_L(alpha,beta,v,kl0,kl);
Fl=Rwb*L;

Mdl=Calculate_Mh(alpha,beta,v,w,km0,km,k1,k2);
Mh=Rwb*Mdl;

F=Fg+Fb+Fd+Fl;
M=Mg+Mh;

end

function D=Calculate_D(alpha,beta,v,kd0,kd)

d=(kd0+kd*alpha*alpha)*norm(v)*norm(v);
D=[-d;0;0];

end

function L=Calculate_L(alpha,beta,v,kl0,kl)
l=(kl0+kl*alpha)*norm(v)*norm(v);
L=[0;0;-l];
end

function Mdl=Calculate_Mh(alpha,beta,v,w,km0,km,k1,k2)
m=(km0+km*alpha)*norm(v)*norm(v);
Mdl=[0;m;0]-k1*w;
% -k2*[0;w(2)*w(2);0];
end
